// these are the data from people you see in your timeline as posts that you ca like and comment on them
export const Users = [
  {
    id:1,
    profilePicture: "assets/person/code1.jpg",
    username: "Isaac Shinini",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell juliet Samoane",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Mwakideo",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dorothy Nduta",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Handsam",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Ruto",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Akoko",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Doubting Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Mitchelle Michigan",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "William Walibora",
  },
  {
    id:11,
    profilePicture: "assets/person/10.jpeg",
    username: "Jame Dickens",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Coding has never been easy... afterall everyone would have done it anyway but l can confirm its exemplinary cool and nice to know how to code ...hit the like btton and leave a comment if interested in coding",
    photo: "assets/post/code1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/business1.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/business2.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Travelling is my next best hobby as l like to travell alot moreso,on business trips where you get to know new ideas from new people from new places. ",
    photo: "assets/post/travel1.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/news2.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "sometimes a little madness can work mostly when it comes to politics !.",
    dec: "GEN-Z oyeee!!! .",
    photo: "assets/post/politics2.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    photo: "assets/post/politics1.jpg",
    date: "1k weeks ago",
    userId: 11,
    like: 1024,
    comment: 12000,
  },
];
